# Generated by Django 3.1.2 on 2020-10-20 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('tour_name', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('registration', models.CharField(blank=True, max_length=255, null=True)),
                ('INN', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('SNILS', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('match_grade', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspectionact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juror', models.IntegerField()),
                ('parallel_officer', models.IntegerField()),
                ('status', models.CharField(max_length=50, null=True)),
                ('disqualification', models.IntegerField()),
                ('disqualification_reason', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True)),
                ('lat', models.CharField(max_length=20, null=True)),
                ('lon', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='formula_app.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Olympiadplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.CharField(max_length=100, null=True)),
                ('check_themself', models.IntegerField()),
                ('trust', models.CharField(max_length=100, null=True)),
                ('reception_date', models.DateTimeField(auto_now=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiad')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='formula_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('can_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schoolyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_camp_participation', models.CharField(blank=True, max_length=255, null=True)),
                ('achievements', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('is_student', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('avatar', models.ImageField(null=True, upload_to='profiles')),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('new_email', models.EmailField(max_length=254, null=True)),
                ('bun_time', models.DateTimeField(null=True)),
                ('bun_reason', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(max_length=30, null=True, unique=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula_app.location')),
                ('role', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='formula_app.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('points', models.IntegerField()),
                ('note', models.CharField(max_length=255, null=True)),
                ('inspection_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.inspectionact')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.grade')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.organization')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='RussianRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russionregion', to='formula_app.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('note', models.CharField(max_length=255, null=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiad')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='formula_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, null=True)),
                ('contacts', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='formula_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Olympiadwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel', models.CharField(max_length=255, null=True)),
                ('file_path', models.FileField(upload_to='olypiadworks')),
                ('status', models.CharField(max_length=255, null=True)),
                ('points', models.IntegerField()),
                ('note', models.CharField(max_length=255, null=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.employee')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.language')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiad')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.result')),
                ('round_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.round')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Olympiadplaceround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiad')),
                ('olympiad_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiadplace')),
                ('round_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.round')),
            ],
        ),
        migrations.AddField(
            model_name='olympiadplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.place'),
        ),
        migrations.CreateModel(
            name='Olympiadjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.employee')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiad')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.position')),
            ],
        ),
        migrations.CreateModel(
            name='Olympiadcompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='olympiad',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.schoolyear'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.speciality'),
        ),
        migrations.AddField(
            model_name='location',
            name='russionregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='formula_app.russianregion'),
        ),
        migrations.AddField(
            model_name='inspectionact',
            name='olypiad_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.olympiadwork'),
        ),
        migrations.CreateModel(
            name='Groupjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.employee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.group')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.position')),
            ],
        ),
        migrations.CreateModel(
            name='Groupcompetitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.schoolyear'),
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.speciality'),
        ),
        migrations.AddField(
            model_name='grade',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.language'),
        ),
        migrations.CreateModel(
            name='Externalactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('other_organization', models.CharField(max_length=255, null=True)),
                ('activity', models.CharField(max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255, null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.camp')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.position')),
            ],
        ),
        migrations.CreateModel(
            name='CampGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.camp')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula_app.location'),
        ),
    ]
