# Generated by Django 3.1.2 on 2020-10-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0004_camp_tour_name_suffics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='russionregion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='formula_app.russianregion'),
        ),
    ]
