# Generated by Django 3.1.2 on 2020-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0005_auto_20201022_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='tour_name_suffics',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
