# Generated by Django 3.1.2 on 2020-10-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0006_auto_20201022_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contract',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='contact',
            new_name='contract',
        ),
        migrations.AlterField(
            model_name='campjob',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campjobs', to='formula_app.employee'),
        ),
        migrations.AlterField(
            model_name='externalactivity',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalactivity', to='formula_app.employee'),
        ),
        migrations.AlterField(
            model_name='groupjob',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupjobs', to='formula_app.employee'),
        ),
        migrations.AlterField(
            model_name='olympiadjob',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiadjob', to='formula_app.employee'),
        ),
    ]
